### ISSUE TITLE
Accuracy calculation

### ISSUE THREAD

**Issue by LoicBne** [chesspecker/feedback#12]
Hello, 
I was doing a packer session for the 3rd time. 

For this third session, I resolved few problems with 100% success, but the accuracy on the dashboard displays 80%.

Is it normal ?

Thanks,
Loïc

**Comment by pnxdxt** [comment]
I had a look, everything seems fine. But I am currently considering changing how the accuracy is calculated because many other users reported having trouble like this one. Will keep you updated!

**Comment by pnxdxt** [comment]
Hi @LoicBne 

Thank you so much for your support ❤️

Here is a little update on this issue.
We are currently working on a new version of the app, containing an improved dashboard page, we are getting rid of this average calculation and replacing it with more precise statistics!

We hope to ship this version in the next few weeks!
